### ISSUE TITLE
[regression in 0.6.5] No rule to make target 'data/???.pclx', needed by 'qrc_tests.cpp'.  Stop.

### ISSUE THREAD

**Issue by yurivict** [pencil2d/pencil#1410]
Please fix this error.

Please also make tests conditional on a compile-time option so that package builders wouldn't need to build tests.

**Comment by chchwy** [comment]
Hey @yurivict, 
Doesn't FreeBSD support Unicode filename?

For the time being you can skip building tests by commenting out line 10 and line 18 in `pencil2d.pro`

```python
SUBDIRS = \ # sub-project names
    core_lib \
    app
#   tests

# build the project sequentially as listed in SUBDIRS !
CONFIG += ordered

# where to find the sub projects - give the folders
core_lib.subdir = core_lib
app.subdir      = app
#tests.subdir    = tests
```

**Comment by yurivict** [comment]
Unicode file names are supported.

In order to update the port I commented out the lines you pointed out. However, this should be done by a variable.

**Comment by chchwy** [comment]
Yes, I can add the variable if needed.

Just wonder why the error happened as it passes our mac/linux CI services.
The filename is intentionally added to test Unicode filenames.

**Comment by yurivict** [comment]
UTF8 filenames are definitely supported.

**Comment by chchwy** [comment]
Must be something in the toolchain that cannot handle unicode filename correctly. 
Anyway I will made that flag later on.

**Comment by chchwy** [comment]
@yurivict can you please check this [PR](https://github.com/pencil2d/pencil/pull/1411), see if it's working on FreeBSD?

**Comment by yurivict** [comment]
It builds fine with these patches.

**Comment by chchwy** [comment]
Fixed in #1411

**Comment by scribblemaniac** [comment]
@Jose-Moreno is experiencing this same issue on Windows with the MinGW compiler. This issue isn't really fixed, only worked-around. I think we should look into the root cause of this and try to find a solution.

**Comment by yurivict** [comment]
I re-tested with qt-5.15.0 and this doesn't happen any more. Might have been a problem with the previous version of Qt.

**Comment by yurivict** [comment]
For the record: qmake needs a UTF8 locale to work properly on the ```pencil2d``` project due to UTF8 characters present in resource file names.

Setting ```USE_LOCALE=en_US.UTF-8``` in a FreeBSD port does this. Other systems should have similar settings available.

**Comment by chchwy** [comment]
I removed the CJK filenames from the `tests.qrc` in commit 2ce3676. I found a way to run the CJK character filename tests without having unicode in the Qt resource system. Let me know if anyone still gets any build errors.
