### ISSUE TITLE
Failed build on Windows 10 "No rule to make target ... libcore_lib.a, needed by '../bin/pencil2d.exe'"

### ISSUE THREAD

**Issue by bergschd** [pencil2d/pencil#1544]
### Issue Summary
Followed the instructions for Windows at:
https://github.com/pencil2d/pencil/wiki/Building-Pencil2D-on-Windows
and ended up with a build error:

`No rule to make target 'C:/path/to/my/cloned/repo/build-pencil2d-Desktop_Qt_5_15_2_MinGW_64_bit-Debug/app/../core_lib/libcore_lib.a', needed by '../bin/pencil2d.exe'.  Stop.`

### Actual Results
See above error message. Project does not build.

### Expected Results
pencil2d running in QC in debug mode

### Steps to reproduce
- running Windows 10
- downloaded and installed Qt Creator, system info says it is version 5.15.2
- cloned  source code with git
- opened pencil2d.pro
- debug option was already selected, clicked green arrow to run

### System Information
+ Pencil2D Version:
Not a release version, cloned from master branch at
https://github.com/pencil2d/pencil
on Dec 5 2020

+ Operating System:
Windows 10

+ RAM Size:
8 GB

**Comment by chchwy** [comment]
Hey @bergschd 
The compiler error has just been fixed in the latest master branch. Can you please pull and try again?

**Comment by Jose-Moreno** [comment]
@chchwy This is still happening in 5.14.1 for me as well even after your commit fix, I posted this on discord but I'll post it again here for easy tracking:

```
:-1: error: No rule to make target 'E:/src/Pencil2D/build-pencil2d-Desktop_Qt_5_14_1_MinGW_64_bit-Debug/app/../core_lib/debug/libcore_lib.a', needed by '../bin/pencil2d.exe'.  Stop.
```

I thought this had been fixed originally by CandyFace's fix here https://github.com/pencil2d/pencil/pull/1318 but somehow this surfaced again. That said your fix https://github.com/pencil2d/pencil/commit/4b65635f3797ec76a8a5adcc15ee4b827da263b3 didn't seem to fully address the issue.

I'm using:
**Edition**: Windows 10 Pro
**Version**: 1909
**OS Build**: 18363.1256

In fact it was working good before the `$$BUILDTYPE` regression. I understand you and @CandyFace also had this conversation before here: https://github.com/pencil2d/pencil/pull/1318#pullrequestreview-389656031 and his solution worked for 5.14 and lower, however does this mean that we have to update QT so `$$BUILDTYPE` works for us now?

I'll post the error log here just in case as well
```
12:22:44: Running steps for project pencil2d...
12:22:44: Configuration unchanged, skipping qmake step.
12:22:44: Starting: "E:\Qt\Tools\mingw730_64\bin\mingw32-make.exe" -j6
E:\Qt\5.14.1\mingw73_64\bin\qmake.exe -o Makefile ..\josemoreno-pencil-master\pencil2d.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
cd core_lib\ && ( if not exist Makefile E:\Qt\5.14.1\mingw73_64\bin\qmake.exe -o Makefile E:\src\Pencil2D\josemoreno-pencil-master\core_lib\core_lib.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && E:/Qt/Tools/mingw730_64/bin/mingw32-make -f Makefile 
mingw32-make[1]: Entering directory 'E:/src/Pencil2D/build-pencil2d-Desktop_Qt_5_14_1_MinGW_64_bit-Debug/core_lib'
mingw32-make[1]: Nothing to be done for 'first'.
mingw32-make[1]: Leaving directory 'E:/src/Pencil2D/build-pencil2d-Desktop_Qt_5_14_1_MinGW_64_bit-Debug/core_lib'
cd app\ && ( if not exist Makefile E:\Qt\5.14.1\mingw73_64\bin\qmake.exe -o Makefile E:\src\Pencil2D\josemoreno-pencil-master\app\app.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && E:/Qt/Tools/mingw730_64/bin/mingw32-make -f Makefile 
mingw32-make[1]: Entering directory 'E:/src/Pencil2D/build-pencil2d-Desktop_Qt_5_14_1_MinGW_64_bit-Debug/app'
mingw32-make[1]: Leaving directory 'E:/src/Pencil2D/build-pencil2d-Desktop_Qt_5_14_1_MinGW_64_bit-Debug/app'
mingw32-make[1]: *** No rule to make target 'E:/src/Pencil2D/build-pencil2d-Desktop_Qt_5_14_1_MinGW_64_bit-Debug/app/../core_lib/debug/libcore_lib.a', needed by '../bin/pencil2d.exe'.  Stop.
mingw32-make: *** [Makefile:94: sub-app-make_first-ordered] Error 2
12:22:54: The process "E:\Qt\Tools\mingw730_64\bin\mingw32-make.exe" exited with code 2.
Error while building/deploying project pencil2d (kit: Desktop Qt 5.14.1 MinGW 64-bit)
When executing step "Make"
12:22:54: Elapsed time: 00:10.
```

**Comment by chchwy** [comment]
Hey @Jose-Moreno sorry for the late reply. I am afraid that you need to upgrade your Qt SDK.

The MinGW path issue happens only in two specific Qt versions: 5.14.0 and 5.14.1. And It has been fixed in 5.14.2. Therefore #1318 is not applicable for 5.14.2 and all later versions. What I have done is ignoring 5.14.0 and 5.14.1 and do it in a more general way for all Qt versions except these two versions.

If you haven't got time to upgrade your Qt, please simply delete the `$$BUILDTYPE` in `app.pro` and `tests.pro`. I believe it will work as a temporary fix.

```diff
- LIBS += -L$$OUT_PWD/../core_lib/$$BUILDTYPE/ -lcore_lib
+ LIBS += -L$$OUT_PWD/../core_lib/ -lcore_lib
- PRE_TARGETDEPS += $$OUT_PWD/../core_lib/$$BUILDTYPE/libcore_lib.a
+ PRE_TARGETDEPS += $$OUT_PWD/../core_lib/libcore_lib.a```
