### ISSUE TITLE
Zoom out with mouse wheel is broken

### ISSUE THREAD

**Issue by handyrka** [pencil2d/pencil#1711]
### Issue Summary

 

When zooming out using mouse wheel, it skips to 1%.
I was also switching distros and had same issue on Fedora and Void Linux. 

### Actual Results

 

Zoom is 1%

### Expected Results

 

Smooth zoom out

### Video or Image Reference

 

[Video reference](https://youtu.be/IjpU8_zuR7I)

### Steps to reproduce

 

Download Pencil2d package on arch:
1. `sudo pacman -S pencil2d`
2. Open Pencil2D 
3. Try to zoom out

### System Information
+ Pencil2D Version: Development Build Feb 27 2021

 

+ Operating System: Arch Linux (KDE, kernel 5.17.5-arch1-1, QT Version 5.15.3)

 

+ RAM Size: 12GB

 

+ Graphics Tablet: I use mouse.

**Comment by Jose-Moreno** [comment]
@handyrka Hi. It's possible this issue has been fixed in the latest versions since there was an enhancement made to the zooming code a few months ago with these PR's https://github.com/pencil2d/pencil/pull/1404 https://github.com/pencil2d/pencil/pull/1487

For now please check the https://www.pencil2d.org/download/nightly/ page and download the appropriate appimage for the latest development version, or you can also pull the code from this repository and compile it with Qt if you feel it's more appropriate.

If while using the latest version you still find the same issue please let us know, otherwise please close this issue 😄

**Comment by handyrka** [comment]
> @handyrka Hi. It's possible this issue has been fixed in the latest versions since there was an enhancement made to the zooming code a few months ago with these PR's #1404 #1487
> 
> For now please check the https://www.pencil2d.org/download/nightly/ page and download the appropriate appimage for the latest development version, or you can also pull the code from this repository and compile it with Qt if you feel it's more appropriate.
> 
> If while using the latest version you still find the same issue please let us know, otherwise please close this issue smile

Unfortunately the problem is still present in latest Nightly build (2022-05-03).

**Comment by handyrka** [comment]
![image](https://user-images.githubusercontent.com/102267165/167508913-b06e40cd-e6f2-4af7-a898-fa5f882047d5.png)
As you can see i did compile it manually, still no luck, issue is still present 😔

**Comment by handyrka** [comment]
Ok i did a little debugging and found a small problem with math in zoom code (Keep in mind i started with zoom 4.8)
If i scroll down, delta is -120
If i scroll up, delta is 120

Here i zoomed in and math seems to work fine:
![image](https://user-images.githubusercontent.com/102267165/167514751-6b150acd-4ea7-4368-846f-d25c9adc478a.png)

But then i zoomed out:
![image](https://user-images.githubusercontent.com/102267165/167514873-7477a377-d3dd-49ec-a53d-aa2d4dc3e27e.png)

As you can see, newScale is negative, and then in function ViewManager::scaleWithOffset we have bounds check. Then it sets newScale to 0.1:
![image](https://user-images.githubusercontent.com/102267165/167514997-8c0ba887-19e5-4224-af80-607b2ccc9ace.png)

**Comment by handyrka** [comment]
![image](https://user-images.githubusercontent.com/102267165/167517405-47ff8599-348e-4d23-80d8-481534c540fc.png)
And this fixed it for me. (At least its working now)

**Comment by MrStevns** [comment]
Thanks for reporting this, although the bug seems to be platform specific, or related to the mouse you're using. 

What I would expect here is that you would trigger the second condition, because the first is made for high precision scrolling, ie. macbook magic pad with gesture and the like where the delta is usually much smaller.

I just tried plugging in my mouse and zooming works as expected (Mac OS) but while my Trackball was also reported as a high precision device, it also triggered far lower delta's than what you get.

What qt writes themselves "Most mouse types work in steps of 15 degrees, in which case the delta value is a multiple of 120; i.e., 120 units * 1/8 = 15 degrees."
so your delta makes sense based on that, I just don't get why it reports pixel based delta's at all... but yeah it looks like we might want check the device type, to make sure that we don't apply pixel based scrolling on something that doesn't use it.

@scribblemaniac do you have any ideas about this, is this something you have seen?

**Comment by handyrka** [comment]
> Thanks for reporting this, although the bug seems to be platform specific, or related to the mouse you're using.
> 
> What I would expect here is that you would trigger the second condition, because the first is made for high-resolution scrolling, ie. macbook magic pad with gesture and the like where the delta is usually much smaller.
> 
> I just tried plugging in my mouse and zooming works as expected (Mac OS) but while my Trackball was also reported as a high-resolution device, it also triggered far lower delta's than what you get.
> 
> What qt writes themselves "Most mouse types work in steps of 15 degrees, in which case the delta value is a multiple of 120; i.e., 120 units * 1/8 = 15 degrees." so your delta makes sense based on that, I just don't get why it reports pixel based delta's at all... but yeah it looks like we might want check the device type, to make sure that we don't apply pixel based scrolling on something that doesn't use it.
> 
> @scribblemaniac do you have any ideas about this, is this something you have seen?

Well my mouse does work fine in other apps, so i wouldn't bet on that. In QT Documentation it states: `Note: On X11 this value is driver specific and unreliable, use [angleDelta](https://doc.qt.io/qt-5/qwheelevent.html#angleDelta)() instead` and i do in fact use X11+Plasma. So yeah it seems like platform specific bug.

**Comment by dexgs** [comment]
@MrStevens, I think your assessment is correct. I found this issue after running into this problem myself on my desktop computer. Out of curiosity, I installed Pencil2D on my laptop as well and I did not experience the same issue using its built-in pointing device. However, I was able to reproduce the issue on the laptop if I used the mouse from my desktop.

**Comment by handyrka** [comment]
I had an idea after seeing dexgs' message. I installed windows on my spare hard drive and run pencil2d. Using the exact same mouse i tried to zoom out and guess what? Issue wasn't present. I'm not sure anymore what is the source of this bug... @dexgs Can you please tell us what OS do you use on your laptop and pc?

**Comment by dexgs** [comment]
> Can you please tell us what OS do you use on your laptop and pc?
Both are running Linux

**Comment by J5lx** [comment]
@dexgs @handyrka I made a change to ignore the pixel deltas on X11, as suggested by the documentation. Can you try running [this build](https://drive.google.com/file/d/1T6_DKj6VQC919bAz4Mds9Qha8dtJIp6a/view?usp=sharing) and confirm whether it fixes the issue?

@MrStevns It sounds like you got both angle-based and pixel-based hardware, can you try updating the pixel-based scrolling to match the angle-based version and check if it performs similarly or if it is necessary to make some tweaks?

**Comment by handyrka** [comment]
@J5lx Yes, i can confirm that the issue is gone now.

**Comment by handyrka** [comment]
Well then i guess is will close this issue. Thank you very much for solving it!

**Comment by J5lx** [comment]
Right now, the fix is still waiting to be merged. We’ll close the issue when it’s merged.
