### ISSUE TITLE
Sketch Tool For https://bitbucket.org/chchwy/pencil2d/downloads/Pencil2D-dev-0.5.4b-win.zip

### ISSUE THREAD

**Issue by Tryen** [pencil2d/pencil#319]
Hello! I'm an independent animator and I loved the feel of the sketch tool and how it looked like a regular pencil (it used my tablet's pressure sensor and the program to make it look so) but now on this new version it's not registering pressure for the sketch tool! All the lines are the same shade, and that's making it more difficult to animate.
Thanks for reading!!!
-Tryen

**Comment by MattJordan** [comment]
Same trouble for me on Linux, although others keep saying it's working for them.

**Comment by tasaif** [comment]
@Tryen @MattJordan What tablets are you using?

**Comment by feeef** [comment]
I fixed this issue a couple of weeks ago. The pencil tool now handles opacity as well as width pressure. @Tryen, if you can get the latest nightly build and confirm that?
Cheers!

**Comment by Tryen** [comment]
I'm still experiencing the same problem, the paintbrush tool works with the pressure sensitivity on my intuos pen and touch tablet (model CTH-480) but the pencil setting did not still

Tryen

**Comment by Jose-Moreno** [comment]
@Tryen Hi. Sorry to bother you, I'm sure you no longer use Pencil2D, but recently we got a new Nightly Build out. Would you mind trying it to see if these problems are solved for you? and If they are could you close this issue resolved. This year a "pressure" checkbox was implemented to activate the pressure sensitivity. This latest build works with my Wacom Intuos Pro 5.

FYI the pencil tool is REALLY light, so you have to exercise some force to see the lines. But Paintbrush (opacity change only) and Pen tool (size change only) work properly.

You can download the latest Oct 10 2016 Nightly Build here: https://drive.google.com/drive/folders/0BxdcdOiOmg-CcWhLazdKR1oydHM

**Comment by Tryen** [comment]
No, I would love to try out the new build! I had stopped using the program, but honestly couldn't find any software I was comfortable with using. I'll download the new build tomorrow, test it out and report back as soon as I can! Thanks for all you've done with the program so far!!

Tryen

**Comment by Tryen** [comment]
Thanks for the update!! Everything on the program works awesome as i remember it!! Pressure sensitivity was a little awkward to figure out at first, but after a little bit of calibration with my tablet it started working really well. There was no in app pressure setting, which threw me off a little bit at first, but like I said before, the tablet comes with that option, so it's a non issue here! One thing I was thinking about was if there was a way to integrate drawings from SAI into Pencil, because while SAI is powerful (albeit confusing) It has no timeline at all, which I despise! Your guy's timeline feature works amazing! I had actually made my very own .GIF with your program, and my girlfriend loved it! But yeah the new update looks and works amazing!

On Oct 16, 2016, at 12:44 PM, Morr <notifications@github.com> wrote:

@Tryen Hi. Sorry to bother you, I'm sure you no longer use Pencil2D, but recently we got a new Nightly Build out. Would you mind trying it to see if these problems are solved for you? and If they are could you close this issue resolved. This year a "pressure" checkbox was implemented to activate the pressure sensitivity. This latest build works with my Wacom Intuos Pro 5.
FYI the pencil tool is REALLY light, so you have to exercise some force to see the lines. But Paintbrush (opacity change only) and Pen tool (size change only) work properly.
You can download the latest Oct 10 2016 Nightly Build here: https://drive.google.com/drive/folders/0BxdcdOiOmg-CcWhLazdKR1oydHM

**Comment by Jose-Moreno** [comment]
@Tryen Well one of our dev friends is actually working hard to integrate MyPaintLib into Pencil. That would mean you  would be able to draw like if you were using MyPaint, and by extension SAI (I've used both and I can attest that MyPaint feels really good to draw). 

The app pressure adjustment is something that has to be worked on as well, although now that you mention it I don't think there's a feature request for that. I'll do it later on so we have that in our TODO checklist. 

The GIF export is new, and you'll get sort of a yellow halo some times, so this will be fixed later. Also be careful when drawing lots of frames. Pencil2D has a memory problem devs are looking into so if you decide to use it a bit more I'd suggest you read this first:

www.pencil2d.org/pencil2d/faq/#corruptfiles

Anyway I'm glad that the program is working better for you now. If you see fit please close this issue to mark it as "solved"

**Comment by Jose-Moreno** [comment]
@chchwy @CandyFace I think we can close this as the OP expressed satisfaction with a Nightly Build from last year.

**Comment by CandyFace** [comment]
Alright, closing.
