### ISSUE TITLE
[ISSUE] There is no warning sign for saving before opening another document

### ISSUE THREAD

**Issue by Kaikogf** [pencil2d/pencil#963]
As title says, I opened an animation and played with the brushes and then decided to open another one  > File > Open Recent > My Animation, and Pencil2D just loaded it without warning about the previous changes and everything was lost

Last compilation Pencil2D 14May2018, Win 8.1

EDITED: When using this path > File > Open , the warning windows pop-up

**Comment by scribblemaniac** [comment]
This should be fixed in the next nightly build, thanks for reporting 🙂

**Comment by Kaikogf** [comment]
Hi @scribblemaniac 

I tested the last version (16April2018) and this issue is still there, it was not fixed.

You have to use the following path to notice it: **_File > Open Recent_**. Doing so, pencil2D will just open the recent file without asking for saving changes made to the previous work.

I tried the last nightly build (21Jun2018) but Qt Creator was not able to build the new code, about 5 errors

ERROR:
"E:\PENCIL2D\pencil-master\pencil-master\core_lib\src\structure\object.h:97: error: 'QFile' has not been declared
     void importPaletteGPL(QFile& file)"

**Comment by Jose-Moreno** [comment]
@Kaikogf I don't understand why you are using April's version since the latest compiled version is from June 20th. Please try that one instead of the one from April.

**Comment by Kaikogf** [comment]
@Jose-Moreno 

I just selected the download link on the community site. Is there any other place?

**Comment by Kaikogf** [comment]
@scribblemaniac @Jose-Moreno 

Everything OK! wrong version of pencil
